version: "3.2"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Cst/UTC
    volumes:
      - /mnt/truenas/lidarr/config:/config
      - /mnt/notpiracy/media/music:/music #optional
      - /mnt/truenas/lidarr/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped