version: "3.2"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Cst/UTC
    volumes:
      - /mnt/truenas/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped