version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas/radarr/config:/config
      - /mnt/truenas/radarr/data:/data
      - /mnt/notpiracy/media/movies:/movies
      - /mnt/notpiracy/media/downloads:/downloads