version: "3.2"
services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas/sonarr/config:/config
      - /mnt/truenas/sonarr/data:/data
      - /mnt/notpiracy/media/shows:/shows