Write-Host "#==============================================================================#"
Write-Host "|                           Powershell Profile v1.0                            |"
Write-Host "|      Commands:                                                               |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "|                                                                              |"
Write-Host "#==============================================================================#"
