version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tnssd/radarr/config:/config
      - /mnt/tnssd/radarr/data:/data
      - /mnt/notpiracy/media/movies:/movies
      - /mnt/notpiracy/media/downloads:/downloads
  
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tnssd/sonarr/config:/config
      - /mnt/tnssd/sonarr/data:/data
      - /mnt/notpiracy/media/shows:/shows
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Cst/UTC
    volumes:
      - /mnt/tnssd/lidarr/config:/config
      - /mnt/notpiracy/media/music:/music #optional
      - /mnt/tnssd/lidarr/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Cst/UTC
    volumes:
      - /mnt/tnssd/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    ports:
      - 8191:8191
    restart: unless-stopped