version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas/radarr/config:/config
      - /mnt/truenas/radarr/data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas/sonarr/config:/config
      - /mnt/truenas/sonarr/data:/data
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8484:8080
      - 9494:9090
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/truenas/sabnzbd/config:/config
      - /mnt/truenas/sabnzbd/data/usenet:/data/usenet:rw