version: "3.8"
services: 
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=eyJhIjoiMGFiOGNiOGE4NDU4ZmViZTRmODQ1NzdiMmY1MmNlMWQiLCJ0IjoiNjAxMDBjZWItZGZhYy00YjdkLWEyY2YtMTIyMzE2NzRlZGVjIiwicyI6IlpUbGtNVGd5TkdVdE56WmxOQzAwTkdRM0xXSTFaRGt0TlRWbE1EYzBPRFV4TXpkaCJ9