version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/truenas/homepage/config:/app/config # Make sure your local config directory exists
      - /mnt/truenas/homepage/images:/app/public/images
    restart: unless-stopped