version: "3.8"
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - 8123:8123
    volumes:
      - /mnt/swarmstorage/homeassistant/config:/config
    restart: unless-stopped