version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - swarmstorage_npm_data:/data
      - swarmstorage_npm_letsencrypt:/etc/letsencrypt
volumes:
  swarmstorage_npm_data:
    external: true
  swarmstorage_npm_letsencrypt:
    external: true