version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/truenas/npm/data:/data
      - /mnt/truenas/npm/letsencrypt:/etc/letsencrypt
    environment:
      - PUID=1001
      - PGID=1001