---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8081
      - PUID=0
      - GUID=0
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/truenas/qbittorrent/config:/config
      - /mnt/truenas/qbittorrent/downloads:/downloads
    ports:
      - 8081:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped