version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 7498:80
            - 8443:443
        environment:
            - PUID=1001
            - PGID=1001
            - DB_CONNECTION=sqlite
            - PUBLIC_DASHBOARD=true
        volumes:
            - /mnt/truenas/speedtest-tracker/config:/config
            - /mnt/truenas/speedtest-tracker/config/keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped